default: &default
  adapter: postgresql
  encoding: unicode
  database: web_for_crist_<%= Rails.env %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: webforchrist
  password: webforchrist

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
