default: &default
  adapter: postgresql
  encoding: unicode
  database: web_for_crist_<%= Rails.env %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: default_user
  password: default_user

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
